name: Github action for publishing package to npm registry

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Publish package to npm registry

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install Node Dependencies
        run: |
          sudo apt-get install libxtst-dev libpng++-dev
          npm install
        env:
          CI: TRUE

      - name: Test Code Linting
        run: npm run lint
        continue-on-error: false

      - name: Running build npm script
        run: npm run build

      - name: Version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = dev ]; then
            npm run version:beta
          else
            npm run version
          fi

          npm run publish
